name: Build and trigger deploy

on:
  push:
    branches: [ "test","staging", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        yarn install
        yarn test:unit
        yarn build
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Trigger Test deploy on vercel
        if: github.ref == 'refs/heads/test'
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_qOjrExrd6cJyyedVNndm4zpwyqhe/HpBmAl3mMF
      - name: Trigger Staging deploy on vercel
        if: github.ref == 'refs/heads/staging'
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_qOjrExrd6cJyyedVNndm4zpwyqhe/ZzyAhboYiC
      - name: Trigger Production deploy on vercel
        if: github.ref == 'refs/heads/master'
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_qOjrExrd6cJyyedVNndm4zpwyqhe/jkzVsazWnN
